[zh]
    # languageName = "简体中文"
    # title        = "Hugo 主题 Stack"
    # weight       = 1

    # [zh.params.sidebar]
    #     subtitle = "为博客设计的卡片式 Hugo 主题"

# [en]
#     languageName = "English"
#     title        = "Hugo Theme Stack"
#     weight       = 2

#     [en.params.sidebar]
#         subtitle = "Card-style Hugo theme designed for bloggers"