[[social]]
    identifier = "CSDN"
    name       = "CSDN"
    url        = "https://blog.csdn.net/weixin_44327736"

    [social.params]
        icon = "csdn"

[[social]]
    identifier = "Gitee"
    name       = "Gitee"
    url        = "https://gitee.com/Gitee-Polaris"

    [social.params]
        icon = "Gitee"

[[social]]
    identifier = "Github"
    name       = "GitHub"
    url        = "https://github.com/Github-Polaris"

    [social.params]
        icon = "brand-github"

